dma/dma/apps/models/__init__.py
from dma import WBalance

dma/dma/apps/models/dma.py
from apps import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin,AnonymousUserMixin
from sqlalchemy import Column,Integer,String,Float
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from flask import current_app,request
import hashlib



class WBalance(db.Model):
    __tablename__ = 'wbalance'
    id = Column('id',db.Integer,primary_key=True)
    name = Column('name',db.String(64),unique=True)
    totoal_in = Column(db.Float)
    auth_use = Column(db.Float)
    loss = Column(db.Float)
    charge_auth = Column(db.Float)
    uncharge_auth = Column(db.Float)
    charge_measure = Column(db.Float)
    charge_unmeasure = Column(db.Float)
    uncharge_measure = Column(db.Float)
    uncharge_unmeasure = Column(db.Float)
    apparent_loss = Column(db.Float)
    actual_loss = Column(db.Float)
    unauth_use = Column(db.Float)
    statistic_error = Column(db.Float)
    money_back = Column(db.Float)
    money_waste = Column(db.Float)
    
    
    def __str__(self):
        return u'%s wbalance' % self.name
    

dma/dma/apps/__init__.py
import os
from flask import Flask,render_template
from flask_bootstrap import Bootstrap
from config import config
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from flask_mail import Mail

app = Flask(__name__)
app.config.from_object(config[os.getenv('FLASK_CONFIG') or 'default'])

bootstrap = Bootstrap()
bootstrap.init_app(app)

mail = Mail()
mail.init_app(app)

db = SQLAlchemy()
db.init_app(app)

from main import main as main_blueprint
app.register_blueprint(main_blueprint)  #,url_prefix='/main'
    
# login_manager = LoginManager()
# login_manager.session_protection='strong'
# login_manager.login_view = 'auth.login'
# login_manager.init_app(app)



from apps.models import WBalance
#from . import views

#app.register_blueprint(auths.mod)


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)
    
    bootstrap.init_app(app)
    db.init_app(app)
    
    #login_manager.init_app(app)
    
    #blueprints
    # from cms import cms as cms_blueprint
    # app.register_blueprint(cms_blueprint,url_prefix='/cms')
    
    # from auth import auth as auth_blueprint
    # app.register_blueprint(auth_blueprint)
    
    # from blog import blog as blog_blueprint
    # app.register_blueprint(blog_blueprint)
    
    return app

dma/dma/apps/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from . import views

dma/dma/apps/main/views.py
from flask import Blueprint,render_template,url_for,redirect,session,request,flash
from apps import app,db

from apps.models import WBalance

from . import main



@main.route('/')
def index():
    
    return render_template('index.html')
    
@main.route('/wbalance')
def wbalance():
    return render_template('main/wbalance.html')

@main.route('/wstasitc')
def wstasitc():
    return 'adsfds'

@main.route('/wdma')
def wdma():
    balance = WBalance.query.order_by(WBalance.name).all()
    month_group = [ba.name for ba in balance ]
    return render_template('main/dma.html',balance=balance[0],month_group=month_group,current_mon=month_group[0])
    
@main.route('/wdma/<mon>')
def wdma_mon(mon):
    balance = WBalance.query.order_by(WBalance.name).all()
    month_group = [ba.name for ba in balance ]
    balance1 = WBalance.query.filter_by(name=mon).first()
    return render_template('main/dma.html',balance=balance1,month_group=month_group,current_mon=mon)

dma/dma/apps/templates/main/dma.html
{% extends "base.html" %}

{% block title %}DMA |wbalance {{ title }}{% endblock %}

<!-- head -->
{% block head %}
    {{ super() }}
    <link href="{{ url_for('static',filename='css/wbalance.css') }}" rel="stylesheet">

<style type="text/css">    
.sidebarContent {
    margin-top: 50px;
    margin-right: 1px;
    margin-bottom: -5px;
    margin-left: -10px;
    height:600px;
    width:150px;
    background-color:silver;
    text-align:center;
    
    display:table-cell;
    vertical-align: middle;
}

.sidebarContent2 {
    margin-top: 1px;
    margin-right: -25px;
    margin-bottom: 1px;
    margin-left: -25px;
    height:300px;
    width:150px;
    background-color:silver;
    text-align:center;
    
    display:table-cell;
    vertical-align: middle;
}

.sidebarContent3 {
    margin-top: 1px;
    margin-right: -30px;
    margin-bottom: 1px;
    margin-left: 1px;
    height:150px;
    background-color:silver;
    text-align:center;
    
    display:table-cell;
    vertical-align: middle;
}

.sidebarContent4 {
    margin-top: 1px;
    margin-right: 1px;
    margin-bottom: 1px;
    margin-left: 1px;
    height:75px;
    background-color:silver;
    text-align:center;
    
    
}

.sidebarContent5 {
    margin-top: 1px;
    margin-right: 1px;
    margin-bottom: 1px;
    margin-left: 1px;
    height:150px;
    background-color:silver;
    text-align:center;
    
    #display:table-cell;
    vertical-align: middle;
}

.sidebarContent6 {
    margin-top: 1px;
    margin-right: 1px;
    margin-bottom: 1px;
    margin-left: 1px;
    height:450px;
    background-color:silver;
    text-align:center;
    
    display:table-cell;
    vertical-align: middle;
}

.content {
    text-align:center;
}

.tophead {
    margin-top: 1px;
    margin-right: 1px;
    margin-bottom: 1px;
    margin-left: 1px;
    height:20px;
    width:1200px;
    #background-color:silver;
    text-align:center;
    
    display:table-cell;
    horizon-align: middle;
}

</style>
{% endblock %}

{% block content %}


    
    <div class="container" >
    
    
        <div class="row">
            <div class="col-xs-12">
                <div class="tophead">
                    <h2>{{ current_mon }}以下期间以m3计之水平衡 30 日</h2>
                </div>
            </div>
        </div>
        <div class="row">
        
        <aside class="col-sm-3 ml-sm-auto blog-sidebar">
          
          <div class="sidebar-module">
            <h4>Monthly</h4>
            <ol class="list-unstyled">
            {% for mon in month_group %}
              <li><a href="{{ url_for('main.wdma_mon',mon=mon) }}">{{ mon }}</a></li>
              
            {% endfor %}
            </ol>
          </div>
          
        </aside><!-- /.blog-sidebar -->
        
        <div class="col-xs-9">
            <div class="col-xs-2">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="sidebarContent">
                            <p>系统进水量<br><br>{{ balance.totoal_in }}[立方米]<br>误差幅度[+/-]:1.0%</p>
                        
                        </div>
                    </div>
                </div>
                
            </div>
            <div class="col-xs-8">
                <div class="row">
                    <!-- middle up -->
                    <div class="col-xs-12">
                        <div class="row">
                            <div class="col-xs-2">
                                <div class="sidebarContent2">
                                    <p>授权用水量<br><br>{{ balance.auth_use }}[立方米]<br>误差幅度[+/-]:1.0%</p>
                                </div>
                            </div>
                            <div class ="col-xs-10">
                                <!-- side 3 up -->
                                <div class="row">
                                    <div class="col-xs-2">
                                        <div class="sidebarContent3">
                                            <p>收费授权用水量<br>{{ balance.charge_auth }}[立方米]</p>
                                        </div>
                                    </div>
                                    <div class="col-xs-10">
                                        <div class="sidebarContent4">
                                            <p>计量收费用水量<br>{{ balance.charge_measure }}[立方米]</p>
                                        </div>
                                    </div>
                                    <div class="col-xs-10">
                                        <div class="sidebarContent4">
                                            <p>未计量收费用水量<br>{{ balance.charge_unmeasure }}[立方米]</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class ="col-xs-10">
                                <!-- side 3 down -->
                                <div class="row">
                                    <div class="col-xs-2">
                                        <div class="sidebarContent3">
                                            <p>未授权用水量<br><br>{{ balance.uncharge_auth }}[立方米]<br>误差幅度[+/-]:2.1%</p>
                                        </div>
                                    </div>
                                    <div class="col-xs-10">
                                        <div class="sidebarContent4">
                                            <p>未收费计量用水量<br>{{ balance.uncharge_measure }}[立方米]</p>
                                        </div>
                                    </div>
                                    <div class="col-xs-10">
                                        <div class="sidebarContent4">
                                            <p>未收费未计量用水量<br>{{ balance.uncharge_unmeasure }}[立方米]<br>误差幅度[+/-]:3.0%</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <!-- middle down -->
                    <div class="col-xs-12">
                        <div class="row">
                            <div class="col-xs-2">
                                <div class="sidebarContent2">
                                    <p>水损失<br>{{ balance.loss }}[立方米]<br>误差幅度[+/-]:4.8%</p>
                                </div>
                            </div>
                            <div class ="col-xs-10">
                                <!-- side 3 up -->
                                <div class="row">
                                    <div class="col-xs-2">
                                        <div class="sidebarContent3">
                                            <p>表观损失水量<br><br>{{ balance.apparent_loss }}[立方米]<br>误差幅度[+/-]:1.4%</p>
                                        </div>
                                    </div>
                                    <div class="col-xs-10">
                                        <div class="sidebarContent4">
                                            <p>未授权用水量<br>{{ balance.unauth_use }}[立方米]<br>误差幅度[+/-]:1.2%</p>
                                        </div>
                                    </div>
                                    <div class="col-xs-10">
                                        <div class="sidebarContent4">
                                            <p>用户水表误差及数据处理之误差<br>{{ balance.statistic_error }}[立方米]<br>误差幅度[+/-]:1.4%</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class ="col-xs-10">
                                <!-- side 3 down -->
                                <div class="sidebarContent5">
                                    <p>实际损失水量<br>{{ balance.actual_loss }}[立方米]<br>误差幅度[+/-]:7.6%</p>
                                </div>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="col-xs-2">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="row">
                            <div class="col-xs-12">
                                <div class="sidebarContent3">
                                    <p>得到收入用水量<br>{{ balance.money_back }}[立方米]</p>
                                </div>
                            </div>
                            <div class="col-xs-12">
                                <div class="sidebarContent6">
                                    <p>未得到收入用水量<br>{{ balance.money_waste }}[立方米]<br>误差幅度[+/-]:4.0%</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
            </div>
            
        </div>    
            
        </div>

    </div>
    
    
{% endblock %}

dma/dma/apps/templates/main/wbalance.html
{% extends "base.html" %}

{% block title %}DMA |wbalance {{ title }}{% endblock %}

<!-- head -->
{% block head %}
    {{ super() }}
    <link href="{{ url_for('static',filename='css/wbalance.css') }}" rel="stylesheet">
    
    <style type="text/css">    
    .divTable
    {
        display:  table;
        width:1400px;
        height:600px;
        background-color:#eee;
        border:1px solid  #666666;
        border-spacing:5px;/*cellspacing:poor IE support for  this*/
       /* border-collapse:separate;*/
    }
    
    </style>
{% endblock %}

{% block content %}
<table class="table table-bordered table-dark divTable">
  
  <tbody>
    <tr>
      <td rowspan="7">1</td>
      <td rowspan="4">2</td>
      <td rowspan="2">3</td>
      <td colspan="3">4</td>
      <td rowspan="2">7</td>
    </tr>
    <tr>
      <td colspan="3">4</td>
    </tr>
    <tr>
      <td rowspan="2">3</td>
      <td colspan="3">4</td>
      <td rowspan="5">7</td>
    </tr>
    <tr>
      <td colspan="3">4</td>
    </tr>
    <tr>
      <td rowspan="3">2</td>
      <td rowspan="2">3</td>
      <td colspan="3">4</td>
    </tr>
    <tr>
      <td colspan="3">4</td>
    </tr>
    <tr>
      <td colspan="4">3</td>
    </tr>
  </tbody>
</table>
{% endblock %}