apps/views/auths.py
from datetime import datetime
from flask import Blueprint,render_template,url_for,redirect,session,request,flash
from flask_login import login_user,logout_user,login_required,current_user
from apps.decorators import admin_required
from apps.forms.auths import RegistrationForm,LoginForm,ChangePasswordForm,\
PasswordResetRequestForm,ResetPasswordForm,ChangeEmailForm,EditProfileForm,EditProfileAdminForm
#from .. import db
from apps import db
from apps.models import Users,Role

from apps.email import send_email


mod = Blueprint('auth',__name__)


@mod.before_app_request
def before_requst():
    
    if current_user.is_authenticated:
        current_user.ping()
        if not current_user.confirmed \
                and request.endpoint[:5] != 'auth.':
            return redirect(url_for('auth.unconfirmed'))
            
@mod.route('/user/<username>')
def user(username):
    user = Users.query.filter_by(username=username).first()
    if user is None:
        abort(404)
    return render_template('user.html',user=user,datetime=datetime.utcnow() )

@mod.route('/auth/edit_profile',methods=['GET','POST'])    
@login_required
def edit_profile():
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.location = form.location.data
        current_user.about_me = form.about_me.data
        db.session.add(current_user)
        db.session.commit()
        flash('Your profile has been updated.')
        return redirect(url_for('auth.user',username=current_user.username))
    form.username.data = current_user.username
    form.location.data = current_user.location
    form.about_me = current_user.about_me
    return render_template('auth/edit_profile.html',form=form)
    
@mod.route('/auth/edit_profile/<int:id>',methods=['GET','POST'])    
@login_required
@admin_required
def edit_profile_admin(id):
    user = Users.query.get_or_404(id)
    form = EditProfileAdminForm(user=user)
    if form.validate_on_submit():
        user.username = form.username.data
        user.confirmed = form.confirmed.data
        user.role = Role.query.get(form.role.data)
        user.location = form.location.data
        user.about_me = form.about_me.data
        db.session.add(user)
        db.session.commit()
        flash('Your profile has been updated.')
        return redirect(url_for('auth.user',username=current_user.username))
    form.username.data = user.username
    form.confirmed.data = user.confirmed
    form.role.data = user.role_id
    form.location.data = user.location
    form.about_me = current_user.about_me
    return render_template('auth/edit_profile.html',form=form,user=user)

@mod.route('/auth/unconfirmed/')
def unconfirmed():
    print 'unconfirmed?'
    if current_user.is_anonymous or current_user.confirmed:
        return redirect('/')
    
    return render_template('auth/unconfirmed.html')
    
@mod.route('/auth/confirm/')
@login_required
def resend_confirmation():
    token = current_user.generate_confirmation_token()
    send_email(current_user.email,'Confirm you account',
            '/auth/email/confirm',user=current_user,token=token)
    flash('A new confirmation email has been sent to you by email.')
    return redirect(url_for('.index'))
        
@mod.route('/auth/confirm/<token>')
@login_required
def confirm(token):
    if current_user.confirmed:
        return redirect(url_for('.index'))
    if current_user.confirm(token):
        flash('You have confirmed your account.Thanks!')
    else:
        flash('The confirmation link is invalid or hax expired.')
    return redirect(url_for('.index'))        

@mod.route('/auth/')
def index():
    return render_template('index.html')

@mod.route('/auth/login/',methods=['GET','POST'])
def login():
    form = LoginForm()
    
    if form.validate_on_submit():
        user = Users.query.filter_by(email=form.email.data).first()
        if user is not None and user.verify_password(form.password.data):
            login_user(user,form.remember_me.data)
            return redirect(request.args.get('next') or url_for('blog.index'))
        flash('Invalid username or password.')
        
    return render_template('auth/login.html',form=form)

    
@mod.route('/auth/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.')
    return redirect(url_for('cms.index'))

@mod.route('/auth/register/',methods=['GET','POST'])
def register():
    form = RegistrationForm(request.form)
    
    if request.method == 'POST' and form.validate():
        user = Users(username=form.username.data, password=form.password.data,email=form.email.data,
        )
        
        db.session.add(user)
        db.session.commit()
        token = user.generate_confirmation_token()
        send_email(user.email,'Confirm Your Account',
                'auth/email/confirm',user=user,token=token)
                
        flash('A confirmation email has been sent to you by email')
        return redirect(url_for('.login'))
    return render_template('auth/register.html', form=form)
    
@mod.route('/auth/change_password/',methods=['GET','POST'])
@login_required
def change_password():
    form = ChangePasswordForm()
    if form.validate_on_submit():
        if current_user.verify_password(form.old_password.data):
            current_user.password = form.password.data
            db.session.add(current_user)
            db.session.commit()
            flash('You password has been updated.')
            return redirect(url_for('auth.index'))
        else:
            flash('Invalid password.')
    return render_template('auth/change_password.html',form=form)
    
@mod.route('/auth/reset_password/',methods=['GET','POST'])
def reset_password_request():
    
    form = PasswordResetRequestForm()
    if form.validate_on_submit():
        user = Users.query.filter_by(email=form.email.data).first()
        if user:
            token = user.generate_reset_token()
            send_email(user.email,'Reset you Password',
            '/auth/email/reset_password',user=user,token=token,
            next=request.args.get('next'))
            flash('An email with instructions to rest your password has been sent to you.')
            return redirect(url_for('auth.login'))
        else:
            print 'user is None?'
            flash('This email not registered.')
    return render_template('auth/reset_password.html',form=form)
    
@mod.route('/auth/reset_password/<token>',methods=['GET','POST'])
def reset_password(token):
    form = ResetPasswordForm()
    if form.validate_on_submit():
        user = Users.query.filter_by(email=form.email.data).first()
        if user is None:
            return redirect(url_for('auth.index'))
        if user.reset_password(token,form.password.data):
            flash('You password has been reset.')
            return redirect(url_for('auth.login'))
        else:
            return redirect(url_for('auth.index'))
        
    return render_template('auth/reset_password.html',form=form)

    
@mod.route('/auth/change_email/',methods=['GET','POST'])
@login_required
def change_email():
    form = ChangeEmailForm()
    if form.validate_on_submit():
        current_user.email = form.password.email
        db.session.add(current_user)
        db.session.commit()
        flash('You email has been updated.')
        return redirect(url_for('auth.index'))
    
    return render_template('auth/change_email/',form=form)

apps/views/cmss.py
from datetime import datetime
from flask import Blueprint,render_template,url_for,redirect,session,request

mod = Blueprint('cms',__name__)

@mod.route('/')
def index():
    return render_template('index.html')
    
@mod.route('/cms/')
def cms_index():
    return render_template('cms/index.html')
    
@mod.route('/cms/pages')
def pages():
    return render_template('cms/pages.html')

@mod.route('/cms/posts')
def posts():
    return render_template('cms/posts.html')

@mod.route('/cms/users')
def users():
    return render_template('cms/users.html')

    

apps/templates/_macros.html
{% macro leftboard() %}
    <div class="col-md-3">
                    <div class="list-group">
                      <a href="index.html" class="list-group-item active main-color-bg">
                        Dashboard
                      </a>
                      <a href="pages.html" class="list-group-item"><span class="glyphicon glyphicon-list-alt" aria-hidden="true">Pages </span><span class="badge">42</span></a>
                      <a href="posts.html" class="list-group-item"><span class="glyphicon glyphicon-pencil" aria-hidden="true">Posts</span><span class="badge">142</span></a>
                      <a href="users.html" class="list-group-item"><span class="glyphicon glyphicon-user" aria-hidden="true">Users</span><span class="badge">8</span></a>
                      
                    </div>
                    
                    <div class="well">
                        <h4>Disk Space Used</h4>
                        <div class="progress">
                          <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
                            <span class="sr-only">60% Complete</span>
                          </div>
                        </div>
                        <h4>Bandwidth Used</h4>
                        <div class="progress">
                          <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 40%;">
                            <span class="sr-only">60% Complete</span>
                          </div>
                        </div>
                    </div>
                </div>
{% endmacro %}


{% macro render_field(field) %}
    <dt>{{ field.label }}
    <dd>{{ field(**kwargs)|safe }}
        {% if field.errors %}
            <ul class=errors>
            {% for error in field.errors %}
            <li>{{ error }}</li>
            {% endfor %}
            </ul>
        {% endif %}
    </dd>
{% endmacro %}

{% macro pagination_widget(pagination,endpoint) %}
<ul class="pagination">
    <li{% if not pagination.has_prev %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_prev %}{{ url_for(endpoint,page=pagination.page-1,**kwargs)}}{% else %}#{% endif %}">&laquo;</a>
    </li>
    {% for p in pagination.iter_pages() %}
        {% if p %}
            {% if p == pagination.page %}
                <li class="actiive">
                    <a href="{{ url_for(endpoint,page=p,**kwargs)}}">{{ p }}</a>
                </i>
            {% else %}
                <li>
                    <a href="{{ url_for(endpoint,page=p,**kwargs)}}">{{ p }}</a>
                </i>
            {% endif %}
        {% else %}
            <li class="disabled"><a href="#">&hellip;</a></li>
        {% endif %}
    {% endfor %}
    <li{% if not pagination.has_next %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_next %}{{ url_for(endpoint,page=pagination.page+1,**kwargs)}}{% else %}#{% endif %}">&raquo;
        </a>
    </li>
</ul>
{% endmacro %}

apps/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Peng | {{ title }}{% endblock %}

<!-- head -->
{% block head %}
    {{ super() }}
    <link href="{{ url_for('static',filename='css/style.css') }}" rel="stylesheet">
    <script src="http://cdn.ckeditor.com/4.7.1/standard/ckeditor.js"></script>
{% endblock %}

<!-- nav bar -->
{% block navbar %}
    <nav class="navbar navbar-default ">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Administrap</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{{ url_for('cms.index') }}">Dashboard</a></li>
            <li><a href="{{ url_for('cms.pages') }}">Pages</a></li>
            <li><a href="{{ url_for('cms.posts') }}">Posts</a></li>
            <li><a href="{{ url_for('cms.users') }}">Users</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            
            {% if current_user.is_authenticated %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="{{ current_user.gravatar(size=18) }}">  
                        Account <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ url_for('auth.user',username=current_user.username) }}">Profile</a></li>
                        <li><a href="{{ url_for('auth.change_password') }}">Change Password</a></li>
                        <li><a href="{{ url_for('auth.change_email') }}">Change Email</a></li>
                        <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
                    </ul>
                </li>
                {% else %}
                <li><a href="{{ url_for('auth.login') }}">Sign In</a></li>
                
                {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
{% endblock %}



<!-- contents -->
{% block content %}
    <header id="header">
        <div class="container">
            <div class="row">
                <div class="col-md-10">
                    <h1><span class="glyphicon glyphicon-cog" aria-hidden="true"></span>Dashboard<small>Manage your site</small></h1>
                </div>
                <div class="col-md-2">
                    <div class="dropdown create">
                      <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        Create Content
                        <span class="caret"></span>
                      </button>
                      <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                        <li><a type="button" data-toggle="modal" data-target="#addPage">Add Page</a></li>
                        <li><a href="#">Add Post</a></li>
                        <li><a href="#">Add User</a></li>
                        
                      </ul>
                    </div>
                </div>
            </div>
        </div>
    </header>
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    
</div>

    
{% endblock %}

<!-- scripts -->
{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
    <script src="http://cdn.ckeditor.com/4.7.1/standard/ckeditor.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
{% endblock %}

apps/templates/blog_create.html
{% extends 'admin/model/create.html' %}
{% import 'rule_dm.html' as rule_demo %}

{#
{% block brand %}
    <h2 id="brand">Create {{ admin_view.name|capitalize }}</h2>
    <div class="clearfix"></div>
    <hr>
{% endblock %}

{% block body %}
  {% call lib.form_tag(form) %}
      {{ lib.render_form_fields(form, form_opts=form_opts) }}
      <div class="form-buttons">
        {{ lib.render_form_buttons(return_url, extra()) }}
      </div>
  {% endcall %}
{% endblock %}
#}

apps/templates/blog_edit.html
{% extends 'admin/model/edit.html' %} 
{% import 'admin/rule_dm.html' as rule_demo %}

{% block head %}
    {{ super() }}
    <link href="{{ url_for('static',filename='css/style.css') }}" rel="stylesheet">
    <script src="http://cdn.ckeditor.com/4.7.1/standard/ckeditor.js"></script>
{% endblock %}


{% block brand %}
    <h2 id="brand">Edit {{ admin_view.name|capitalize }}</h2>
    <div class="clearfix"></div>
    <hr>
{% endblock %}

{% block body %}
  {% call lib.form_tag(form) %}
      {{ lib.render_form_fields(form, form_opts=form_opts) }}
      <div class="form-buttons">
        {{ lib.render_form_buttons(return_url) }}
      </div>
  {% endcall %}
  
<script>
    CKEDITOR.replace( 'editor1' );
</script>
    
{% endblock %}


apps/templates/blog_list.html
{% extends 'admin/model/list.html' %}
{% import 'admin/model/layout.html' as model_layout with context %}

{% block brand %}
    <h2 id="brand">{{ admin_view.name|capitalize }} list</h2>
    {% if admin_view.can_create %}
    <div class="btn-menu">
        <a href="{{ url_for('.create_view', url=return_url) }}" class="btn btn-primary pull-right">{{ _gettext('Create') }}</a>
    </div>
    {% endif %}

    {% if filter_groups %}
    <div class="btn-group btn-menu">
        {{ model_layout.filter_options(btn_class='btn dropdown-toggle btn-title') }}
    </div>
    {% endif %}

    {% if actions %}
    <div class="btn-group btn-menu">
        {{ actionlib.dropdown(actions, btn_class='btn dropdown-toggle btn-title') }}
    </div>
    {% endif %}

    {% if search_supported %}
    <div class="search-form btn-menu">
        {{ model_layout.search_form(input_class='span2 btn-title') }}
    </div>
    {% endif %}
    <div class="clearfix"></div>
    <hr>
{% endblock %}

{% block model_menu_bar %}
{% endblock %}

apps/templates/content.html
<div class="col-md-9">
                    <div class="panel panel-default">
                      <div class="panel-heading main-color-bg">
                        <h3 class="panel-title">Website Overview</h3>
                      </div>
                      <br>
                      <div class="panel-body">
                        <div class="col-md-3">
                            <div class="well dash-box">
                                <h2><span class="glyphicon glyphicon-user" aria-hidden="true">203</h2>
                                <h4>Users</h4>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="well dash-box">
                                <h2><span class="glyphicon glyphicon-pencil" aria-hidden="true">123</span></h2>
                                <h4>Posts</h4>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="well dash-box">
                                <h2><span class="glyphicon glyphicon-list-alt" aria-hidden="true">203</span></h2>
                                <h4>Pages</h4>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="well dash-box">
                                <h2><span class="glyphicon glyphicon-stats" aria-hidden="true">20345</span></h2>
                                <h4>Visitors</h4>
                            </div>
                        </div>
                        
                      </div>
                    </div>
                    <!-- Latest user  -->
                    <div class="panel panel-default">
                      <!-- Default panel contents -->
                      <div class="panel-heading">Latest User</div>
                      <div class="panel-body">
                        <!-- Table -->
                      <table class="table table-stripped table-hover">
                        <tr>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Joined</th>
                        </tr>
                        <tr>
                            <td>Michal Jordan</td>
                            <td>Chicago</td>
                            <td>June 1,1983</td>
                        </tr>
                        <tr>
                            <td>Michal Jordan</td>
                            <td>Chicago</td>
                            <td>1983</td>
                        </tr>
                      </table>
                      </div>

                      
                    </div>
                </div>

apps/templates/field_list.html
{% import 'admin/model/inline_list_base.html' as base with context %}

{% macro render_field(field) %}
  {% set model = field.object_data %}
  {% if model and model.path %}
    {{ field.form.id }}
    <img src="{{ url_for('static', filename=model.path) }}" style="max-width: 300px;"></img>
  {% else %}
    {{ field }}
  {% endif %}
{% endmacro %}

{{ base.render_inline_fields(field, template, render_field) }}

apps/templates/footer.html
    <footer id="footer">
        <p>Copyright Adminstrap,&copy;2017</p>
    </footer>

apps/templates/index.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}

{% block title%}Peng|Jumbotron Template for Bootstrap{% endblock %}
<!-- head -->
{% block head %}
    {{ super() }}
    <link href="{{ url_for('static',filename='css/jumbotron.css') }}" rel="stylesheet">
{% endblock %}

{% block content %}
    {{ super() }}
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1>Hello, world!</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>learing how to do this. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>CMS</h2>
          <p>learning how to buile cms site with bootstrap. </p>
          <p><a class="btn btn-default" href="/cms/" role="button">View details &raquo;</a></p>
       </div>
        <div class="col-md-4">
          <h2>Blog</h2>
          <p>Peng's blog </p>
          <p><a class="btn btn-default" href="/blog/" role="button">View details &raquo;</a></p>
        </div>
      </div>

      <hr>
    
        
    <script>
        CKEDITOR.replace( 'editor1' );
    </script>
    
    {% include "footer.html" %}

{% endblock %}

apps/templates/layout.html
{% import 'admin/layout.html' as layout with context -%}
{% extends 'admin/base.html' %}

{% block head_tail %}
  {{ super() }}
  <link href="{{ url_for('static', filename='layout.css') }}" rel="stylesheet">
{% endblock %}

{% block page_body %}
<div class="container">
  <div class="row">
    <div class="span2">
      <ul class="nav nav-pills nav-stacked">
        {{ layout.menu() }}
        {{ layout.menu_links() }}
      </ul>
    </div>
    <div class="span10">
      <div id="content">
        {% block brand %}
          <h2 id="brand">{{ admin_view.name|capitalize }}</h2>
          <div class="clearfix"></div>
        {% endblock %}
        {{ layout.messages() }}
        {% set render_ctx = h.resolve_ctx() %} 
        {% block body %}{% endblock %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

apps/templates/modal.html
<!-- Modal -->
    <div class="modal fade" id="addPage" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
        <form>
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">add Page</h4>
          </div>
          <div class="modal-body">
            <div class="form-group">
                <label>Page Title</label>
                <input type="text" class="form-control" placeholder="Page Title">
            </div>
            <div class="form-group">
                <label>Page Body</label>
                <textarea name="editor1" class="form-control" placeholder="pleas input Page contents"></textarea>
            </div>
            <div class="checkbox">
                <label>
                <input type="checkbox" >Published
                </label>
            </div>
            <div class="form-group">
                <label>Meta Tags</label>
                <input type="text" class="form-control" placeholder="add some tags ...">
            </div>
            <div class="form-group">
                <label>Meta Description</label>
                <input type="text" class="form-control" placeholder="Add Meta Descriotion ...">
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Save changes</button>
          </div>
          </form>
        </div>
      </div>
    </div>
    
    

apps/templates/rule_dm.html
{% macro wrap() %}
  <div style="border: 1px solid gray; background-color: #f0f0f0; padding-top: 8px; margin-bottom: 8px">
    {{ caller() }}
  </div>
{% endmacro %}

apps/templates/user.html
{% extends "base.html"%}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}User Profile {% endblock %}

{% block content %}

    <div class="page-header">
        <div class="col-md-3">
            <div class="well dash-box">
                <a href="#" >
                        <img src="{{ current_user.gravatar(size=100) }}">  
                        
                    </a>
            </div>
        </div>
        <h1>{{ user.username }}</h1>
        {% if user == current_user%}
            <a class="btn btn-default" href="{{ url_for('auth.edit_profile')}}">Edit Profile</a>
        {% endif %}
        {% if current_user.is_administrator() %}
            <a class="btn btn-default" href="{{ url_for('auth.edit_profile_admin',id=user.id) }}">Edit Profile[Admin]</a>
        {% endif %}.
        {% if user.name or user.location %}
        <p>
        {% if user.name %}{{ user.name }}{% endif %}
        {% if user.location %}
        From <a href="http://maps.google.com/?q={{ user.location }}">
        {{ user.location }}
        </a>
        {% endif %}
        </p>
        {% endif %}
        {% if current_user.is_administrator() %}
        <p><a href="mailto:{{ user.email }}">{{ user.email }}</a></p>
        {% endif %}
        {% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}
        <p>
        Member since {{ moment(user.member_since).format('L') }}.
        Last seen {{ moment(user.last_seen).fromNow(refresh=True) }}.
        
        </p>
        Time Now :{{ moment(datetime).format('L') }}
    </div>
    
    
{% endblock %}