apps/models/blogs.py
from apps import db
from sqlalchemy import Column,ForeignKey,String,Integer,Table,Text
from sqlalchemy.orm import relationship
from datetime import datetime
from auths import Users



reltags = db.Table('reltags',
    db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'), primary_key=True),
    db.Column('page_id', db.Integer, db.ForeignKey('posts.id'), primary_key=True)
)

    
class BlogPost(db.Model):
    __tablename__ = 'posts'
    
    id = Column(Integer,primary_key=True)
    headline = Column(String(255), nullable=False)
    body = Column(Text)
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    
    user_id = Column(Integer, ForeignKey('users.id'))
    
    
    category_id = db.Column(db.Integer, db.ForeignKey('category.id'))
    category = db.relationship('Category',
        backref=db.backref('posts', lazy='dynamic'))

    
    # many to many BlogPost<->Keyword
    tags = db.relationship('Tag', secondary=reltags, lazy='subquery',
        backref=db.backref('pages', lazy='dynamic'))
    
    
    comments = relationship('Comments',backref='posts',lazy='dynamic')                                
                           
    
    # def __init__(self,headline,body,author):
        # self.author = author
        # self.headline = headline
        # self.body = body
        
    def __repr__(self):
        return "BlogPost(%r, %r, %r)" % (self.headline, self.body, self.author)


class Category(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50))

    # def __init__(self, name):
        # self.name = name
        

    def __repr__(self):
        return '<Category %r>' % self.name




class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)        
    keyword = db.Column(db.String(50))
    
    # def __init__(self,name):
        # self.name = name
        
    def __repr__(self):
        return '<Category %r>' % self.keyword


class Comments(db.Model):
    __tablename__ = 'comments'
    
    id = Column(Integer,primary_key=True)
    guest = Column(String(50))
    body = Column(db.Text)
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    post_id = Column(Integer,db.ForeignKey('posts.id'))
    
    def __repr__(self):
        return "Comment(%r,%r)" %(self.guest,self.body)

apps/forms/blogs.py
from flask_wtf import FlaskForm
from wtforms import Form, BooleanField, StringField, PasswordField, SubmitField,TextAreaField,SelectField
from wtforms.validators import Regexp,Required, Email,Length,DataRequired,EqualTo
from wtforms import ValidationError

class PostBlogForm(FlaskForm):
    title = StringField('Blog Title',validators=[Length(0,256)])
    body = TextAreaField('Blog Content')
    publish = BooleanField('Publish', [DataRequired()])
    category = StringField('category',validators=[Length(0,300)])
    keyword = StringField('keywords',validators=[Length(0,640)])
    submit = SubmitField('Submit')
    
    
class CommentForm(FlaskForm):
    guest = StringField('Guest name',validators=[Length(0,256)])
    body = TextAreaField('Comment')
    submit = SubmitField('Submit')

apps/views/blogs.py
from flask import Blueprint,render_template,redirect,url_for,request
from flask_login import login_required,current_user
from apps import db
from apps.forms.blogs import PostBlogForm,CommentForm
from apps.models import Users,Role,BlogPost,Category,Tag,Comments

mod = Blueprint('blog',__name__)

@mod.route('/blog/',methods=['GET','POST'])
def index():
    page = request.args.get('page',1,type=int)
    # pagination = current_user.posts.order_by(BlogPost.timestamp.desc()).paginate(
            # page,per_page=20,error_out=False
        # )
    #blogs =pagination.items
    blogs = BlogPost.query.order_by(BlogPost.timestamp.desc()).all()
    category = Category.query.all()
    return render_template('blog/index.html',blogs=blogs,pagination=[],category=category)
    
@mod.route('/blog/new_blog/',methods=['GET','POST'])
@login_required
def new_blog():
    form = PostBlogForm()
    if form.validate_on_submit():
        title = form.title.data
        body = form.body.data
        publish = form.publish.data
        category = form.category.data
        keywords = form.keyword.data.split(' ')
        
        cat = Category.query.filter_by(name=category).first()
        if cat is None:
            cat = Category(name=category)
        
        post = BlogPost(headline=title,body=body,author=current_user._get_current_object(),category=cat)#,tags=tag)
        cat.posts.append(post)
        
        for kw in keywords:
            tag = Tag(keyword=kw)
            post.tags.append(tag)
        #tag.posts.append(post)
        
        db.session.add(post)
        #db.session.add(cat)
        #db.session.add(tag)
        db.session.commit()
        
        return redirect(url_for('blog.index'))
    print 'invalid submit?'
    return render_template('blog/new_blog.html',form=form)

@mod.route('/blog/<int:id>',methods=['GET','POST'])
def post(id):
    post = BlogPost.query.get_or_404(id)
    post_total = BlogPost.query.count()
    form = CommentForm()
    if form.validate_on_submit():
        guest = form.guest.data
        body = form.body.data
        comment = Comments(guest=guest,posts=post,body=body)
        db.session.add(comment)
        db.session.commit()
        return redirect(url_for('.post',id=post.id,page=-1))
    page = request.args.get('page', 1, type=int)
    if page == -1:
        page = (post.comments.count() - 1) / 20 + 1
    pagination = post.comments.order_by(Comments.timestamp.asc()).paginate(
    page, per_page=20,    error_out=False)
    comments = pagination.items
    category = Category.query.all()
    return render_template('blog/post.html', blog=post, form=form,
        comments=comments, pagination=pagination,category=category,post_total=post_total)
        
        
@mod.route('/blog/category/<string:catname>')
def category(catname):        
    page = request.args.get('page',1,type=int)
    # pagination = current_user.posts.order_by(BlogPost.timestamp.desc()).paginate(
            # page,per_page=20,error_out=False
        # )
    #blogs =pagination.items
    cate = Category.query.filter_by(name=catname).first()
    blogs = BlogPost.query.filter_by(category=cate).order_by(BlogPost.timestamp.desc()).all()
    category = Category.query.all()
    
    #blogs = [cat.posts for cat in cate]
    return render_template('blog/index.html',blogs=blogs,pagination=[],category=category)

apps/templates/blog/_comments.html
<ul class="comments">

    {% for comment in comments %}

    <li class="comment">
{#
        <div class="comment-thumbnail">

            <a href="{{ url_for('.user', username=comment.author.username) }}">

                <img class="img-rounded profile-thumbnail" src="{{ comment.author.gravatar(size=40) }}">

            </a>

        </div>
#}
        <div class="comment-content">

            <div class="comment-date">{{ moment(comment.timestamp).fromNow() }}</div>

            <div class="comment-author"><a href="{{ url_for('auth.user', username=comment.guest) }}">{{ comment.guest }}</a></div>

            <div class="comment-body">

                {% if comment.disabled %}

                <p><i>This comment has been disabled by a moderator.</i></p>

                {% endif %}

                {% if moderate or not comment.disabled %}

                    {% if comment.body_html %}

                        {{ comment.body_html | safe }}

                    {% else %}

                        {{ comment.body }}

                    {% endif %}

                {% endif %}

            </div>

            {% if moderate %}

                <br>

                {% if comment.disabled %}

                <a class="btn btn-default btn-xs" href="{{ url_for('.moderate_enable', id=comment.id, page=page) }}">Enable</a>

                {% else %}

                <a class="btn btn-danger btn-xs" href="{{ url_for('.moderate_disable', id=comment.id, page=page) }}">Disable</a>

                {% endif %}

            {% endif %}

        </div>

    </li>

    {% endfor %}

</ul>

apps/templates/blog/index.html
{% extends "bootstrap/base.html" %}

{% block title %} Peng's Blog{% endblock %}

{% import "_macros.html" as macros %}

<!-- head -->
{% block head %}
    {{ super() }}
    <link href="{{ url_for('static',filename='css/blog.css') }}" rel="stylesheet">
    <script src="http://cdn.ckeditor.com/4.7.1/standard/ckeditor.js"></script>
{% endblock %}


{% block content %}

    <div class="blog-masthead">
      <div class="container">
        <nav class="blog-nav">
          <a class="blog-nav-item active" href="#">Home</a>
          <a class="blog-nav-item" href="#">New features</a>
          <a class="blog-nav-item" href="#">Press</a>
          <a class="blog-nav-item" href="{{ url_for('blog.new_blog')}}">New Blog</a>
          <a class="blog-nav-item" href="#">About</a>
        </nav>
      </div>
    </div>

    <div class="container">

      

      <div class="row">

        <div class="col-sm-8 blog-main">
        
        {% for blog in blogs %}
        <div class="blog-header">
        <h1 class="blog-title"><a href="{{ url_for('blog.post',id=blog.id)}}">{{ blog.headline }}</a></h1>
        <p class="blog-post-meta">{{ blog.timestamp }} by <a href="#">{{ blog.author.username }}</a></p>
        </div>
        <div class="blog-post">
            <div>
                {{ blog.body | safe }}
            </div>
        </div>
        
        {% endfor %}
 
        {% if pagination %}
        <div class="pagination">
            {{ macros.pagination_widget(pagination,'.index')}}
        </div>
        {% endif %}
     
          <!-- /.blog-post -->
{#  
          <nav>
            <ul class="pager">
              <li{% if not pagination.has_prev %} class="disabled"{% endif %}>
              <a href="{% if pagination.has_prev%}{{ url_for('.index',page=pagination.page-1)}}{% else %}#{% endif %}">Previous</a></li>
              <li{% if not pagination.has_next %} class="disabled"{% endif %}>
              <a href="{% if pagination.has_next%}{{ url_for('.index',page=pagination.page+1)}}{% else %}#{% endif %}">Next</a></li>
              
            </ul>
          </nav>
#}
        </div><!-- /.blog-main -->

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
          <div class="sidebar-module sidebar-module-inset">
            <h4>About</h4>
            <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
          </div>
          <div class="sidebar-module">
            <h4>Category</h4>
            {% for cat in category %}
            <ol class="list-unstyled">
              <li><a href="{{ url_for('blog.category',catname=cat.name)}}">{{ cat.name }}</a><span class="badge">{{ cat.posts.count() }}</span></li>
              
            </ol>
            {% endfor %}
          </div>
          <div class="sidebar-module">
            <h4>Elsewhere</h4>
            <ol class="list-unstyled">
              <li><a href="#">GitHub</a></li>
              <li><a href="#">Twitter</a></li>
              <li><a href="#">Facebook</a></li>
            </ol>
          </div>
        </div><!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </div><!-- /.container -->

   {% include "footer.html" %}



{% endblock %}

    <!-- scripts -->
{% block scripts %}
    {{ super() }}
    
    <script src="http://cdn.ckeditor.com/4.7.1/standard/ckeditor.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
{% endblock %}

apps/templates/blog/new_blog.html
{% extends "bootstrap/base.html" %}

{% import "bootstrap/wtf.html" as wtf %}

{% block title %} Peng's Blog{% endblock %}

<!-- head -->
{% block head %}
    {{ super() }}
    <link href="{{ url_for('static',filename='css/blog.css') }}" rel="stylesheet">
    <script src="http://cdn.ckeditor.com/4.7.1/standard/ckeditor.js"></script>
{% endblock %}


{% block content %}

    <div class="blog-masthead">
      <div class="container">
        <nav class="blog-nav">
          <a class="blog-nav-item active" href="#">Home</a>
          <a class="blog-nav-item" href="#">New features</a>
          <a class="blog-nav-item" href="#">Press</a>
          <a class="blog-nav-item" href="{{ url_for('blog.new_blog')}}">New Blog</a>
          <a class="blog-nav-item" href="#">About</a>
        </nav>
      </div>
    </div>

    <div class="container">
        <div class="row">

        <div class="col-sm-8 blog-main">

          <div class="blog-post">
            <form action='/blog/new_blog/' method="post">
            
            
            {{ form.csrf_token }}
            
            {{ wtf.quick_form(form) }}

              </form>
            </div>
          </div>
            

          

          

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
          <div class="sidebar-module sidebar-module-inset">
            <h4>About</h4>
            <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
          </div>
          <div class="sidebar-module">
            <h4>Archives</h4>
            <ol class="list-unstyled">
              <li><a href="#">March 2014</a></li>
              <li><a href="#">February 2014</a></li>
              <li><a href="#">January 2014</a></li>
              <li><a href="#">December 2013</a></li>
              <li><a href="#">November 2013</a></li>
              <li><a href="#">October 2013</a></li>
              <li><a href="#">September 2013</a></li>
              <li><a href="#">August 2013</a></li>
              <li><a href="#">July 2013</a></li>
              <li><a href="#">June 2013</a></li>
              <li><a href="#">May 2013</a></li>
              <li><a href="#">April 2013</a></li>
            </ol>
          </div>
          <div class="sidebar-module">
            <h4>Elsewhere</h4>
            <ol class="list-unstyled">
              <li><a href="#">GitHub</a></li>
              <li><a href="#">Twitter</a></li>
              <li><a href="#">Facebook</a></li>
            </ol>
          </div>
        </div><!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </div><!-- /.container -->
    <script>
        CKEDITOR.replace( 'body' );
    </script>

   {% include "footer.html" %}



{% endblock %}

    <!-- scripts -->
{% block scripts %}
    {{ super() }}
    
    <script src="http://cdn.ckeditor.com/4.7.1/standard/ckeditor.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
{% endblock %}

apps/templates/blog/post.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} Peng's Blog{% endblock %}

{% import "_macros.html" as macros %}

<!-- head -->
{% block head %}
    {{ super() }}
    <link href="{{ url_for('static',filename='css/blog.css') }}" rel="stylesheet">
    <script src="http://cdn.ckeditor.com/4.7.1/standard/ckeditor.js"></script>
{% endblock %}


{% block content %}

    <div class="blog-masthead">
      <div class="container">
        <nav class="blog-nav">
          <a class="blog-nav-item active" href="#">Home</a>
          <a class="blog-nav-item" href="#">New features</a>
          <a class="blog-nav-item" href="#">Press</a>
          <a class="blog-nav-item" href="{{ url_for('blog.new_blog')}}">New Blog</a>
          <a class="blog-nav-item" href="#">About</a>
        </nav>
      </div>
    </div>

    <div class="container">

      

      <div class="row">

        <div class="col-sm-8 blog-main">
        
        
        <div class="blog-header">
        <h1 class="blog-title">{{ blog.headline }}</h1>
        <p class="blog-post-meta">{{ blog.timestamp }} by <a href="#">{{ current_user.username }}</a></p>
        </div>
        <div class="blog-post">
            <div>
                {{ blog.body | safe }}
            </div>
        </div>
        
        

          <!-- /.blog-post -->

          <nav>
            <ul class="pager">
              <li{% if blog.id == 1 %} class="disabled"{% endif %}>
              <a href="{{ url_for('blog.post',id=blog.id-1)}}">Previous</a></li>
              <li{% if blog.id == post_total %} class="disabled"{% endif %}>
              <a href="{{ url_for('blog.post',id=blog.id+1)}}">Next</a></li>
              
            </ul>
          </nav>
          
          <ul class="media-list">
          <!-- comment -->
          {% for comment in comments %}
          <li class="media">
          <div class="media-left">
              <a href="#">
                <img class="media-object" src="http://www.gravatar.com/avatar/3b2b619ec6262955cb95161e729e20db?s=18&amp;d=identicon&amp;r=g" alt="...">
              </a>
            </div>

            <div class="media-body">
            <p >{{ moment(comment.timestamp).fromNow()  }} by <a href="#">{{ comment.guest }}</a></p>
                {{ comment.body | safe }}
                
            </div>
            </li>
            {% endfor %}
           </ul>
{#  
        <div class="pagination">
            {{ macros.pagination_widget(pagination,'.post')}}
        </div>
#}        
        <div class="comment-form">
            {{ wtf.quick_form(form) }}
        </div>
  

        </div><!-- /.blog-main -->

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
          <div class="sidebar-module sidebar-module-inset">
            <h4>About</h4>
            <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
          </div>
          <div class="sidebar-module">
            <h4>Category</h4>
            {% for cat in category %}
            <ol class="list-unstyled">
              <li><a href="#">{{ cat.name }}</a><span class="badge">{{ cat.posts.count() }}</span></li>
              
            </ol>
            {% endfor %}
          </div>
          <div class="sidebar-module">
            <h4>Elsewhere</h4>
            <ol class="list-unstyled">
              <li><a href="#">GitHub</a></li>
              <li><a href="#">Twitter</a></li>
              <li><a href="#">Facebook</a></li>
            </ol>
          </div>
        </div><!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </div><!-- /.container -->

   {% include "footer.html" %}



{% endblock %}

    <!-- scripts -->
{% block scripts %}
    {{ super() }}
    
    <script src="http://cdn.ckeditor.com/4.7.1/standard/ckeditor.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
{% endblock %}